import 'package:injectable/injectable.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../../../../core/errors/exceptions.dart';
import '../models/order_model.dart';

abstract class OrderRemoteDataSource {
  Future<OrderModel> createOrder(OrderModel order);
  Future<List<OrderModel>> getOrders(String userId);
  Future<OrderModel> getOrder(String orderId);
}

@LazySingleton(as: OrderRemoteDataSource)
class OrderRemoteDataSourceImpl implements OrderRemoteDataSource {
  final SupabaseClient _supabaseClient;

  OrderRemoteDataSourceImpl(this._supabaseClient);

  @override
  Future<OrderModel> createOrder(OrderModel order) async {
    try {
      final orderData = order.toJson();
      // Remove fields that should be generated by the database if they are null
      orderData.removeWhere((key, value) =>
          (key == 'id' || key == 'created_at' || key == 'updated_at') &&
          value == null);

      final response = await _supabaseClient
          .from('orders')
          .insert(orderData)
          .select()
          .single();

      return OrderModel.fromJson(response);
    } catch (e) {
      throw ServerException(e.toString());
    }
  }

  @override
  Future<List<OrderModel>> getOrders(String userId) async {
    try {
      final response = await _supabaseClient
          .from('orders')
          .select()
          .eq('user_id', userId)
          .order('created_at', ascending: false);

      return (response as List)
          .map((json) => OrderModel.fromJson(json))
          .toList();
    } catch (e) {
      throw ServerException(e.toString());
    }
  }

  @override
  Future<OrderModel> getOrder(String orderId) async {
    try {
      final response = await _supabaseClient
          .from('orders')
          .select()
          .eq('id', orderId)
          .single();

      return OrderModel.fromJson(response);
    } catch (e) {
      throw ServerException(e.toString());
    }
  }
}
